---
# tasks file for doclog_front
- name: Копируем архив с установочными файлами nginx
 copy:
 src: /tmp/nginx.zip
 dest: /tmp/nginx.zip

- name: Разархивируем nginx
 unarchive:
 src: /tmp/nginx.zip
 dest: /tmp/

- name: Установка nginx
 shell: sudo dpkg -i /tmp/nginx/*.deb
 ignore_errors: true

- name: Копируем архив со статикой doclog
 copy:
 src: /tmp/doclog_front.tar.gz
 dest: /var/www/html/doclog_front.tar.gz

- name: Удаление старого билда
 file:
 path: /var/www/html/doclog
 state: absent

- name: Создание папки под static-files doclog
 file:
 path: /var/www/html/doclog
 state: directory

- name: Разархивируем статику
 unarchive:
 src: /var/www/html/doclog_front.tar.gz
 dest: /var/www/html/doclog/
 remote_src: true

- name: Удалим установочные файлы
 file:
 path:
  - /var/www/html/doclog_front.tar.gz
  - /tmp/nginx.zip
 state: absent

- name: Удалим конфигурационный файл nginx
 file:
 path: /etc/nginx/sites-available/default
 state: absent

- name: Копируем конфигурационный файл nginx
 template:
 src: "{{ nginx_template }}"
 dest: /etc/nginx/sites-available/default
 vars:
 server_ip: "{{ ansible_host }}"
 notify:
 - Перезапуск NGINX



