---
- name: Установка psdoi-parsing
 hosts: '{{ hosts }}'
 become: true

 pre_tasks:
 - name: Загрузка psdoi-parsing.tar.gz
  get_url:
   url: http://192.168.5.119:8000/psdoi-parsing.tar.gz
   dest: /tmp/psdoi-parsing.tar.gz
  delegate_to: ansible_host
 
 roles:
  - ../roles/psdoi_parsing