---
- name: Загрузка новых артефактов на ansible_host
 hosts: '{{ hosts }}'
 become: true
 
 pre_tasks:
 - name: Загрузка filebeat
  get_url:
  url: http://192.168.5.119:8000/filebeat_build.tar.gz
  dest: /tmp/
  delegate_to: ansible_host
  
 - name: Загрузка wazuh-module
  get_url:
  url: http://192.168.5.119:8000/filebeat/wazuh-module.tar.gz
  dest: /tmp/
  delegate_to: ansible_host
  
 roles:
 - ../roles/filebeat
  
