---
- name: Установка indexer
 hosts: '{{ hosts }}'
 become: true

 pre_tasks:
 - name: Загрузка indexer.tar.gz
  get_url:
  url: http://192.168.5.119:8000/indexer.tar.gz
  dest: /tmp/indexer_build.tar.gz
  delegate_to: ansible_host

 roles:
 - ../roles/indexer
