---
- name: Установка manager
 hosts: '{{ hosts }}'
 become: true 

 pre_tasks:
 - name: Загрузка manager.tar.gz
  get_url:
  url: http://192.168.5.119:8000/manager_build.tar.gz
  dest: /tmp/manager_build.tar.gz
  delegate_to: ansible_host

 roles:
 - ../roles/manager

